# (Compose version key removed — modern Docker Compose no longer requires it)

services:
  db:
    image: postgres:15-alpine
    container_name: litgo_db
    ports:
      - "54326:5432"
    environment:
      POSTGRES_DB: litgo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: celery -A backend.celery_app worker --loglevel=info

networks:
  default:
    name: litgo_network 

volumes:
  pgdata: 